### ISSUE TITLE
protractor-flake seems to rerun ALL tests when only SOME fail

### ISSUE THREAD

**Issue by bcherny** [NickTomlin/protractor-flake#6]
running via gulpfile:

``` coffee
gulp.task 'e2e', ->
 (require 'protractor-flake')
    '--': ['./protractor.conf.coffee']
    maxAttempts: 3
    protractorPath: './node_modules/.bin/protractor'
```

and the protractor.conf.coffee:

``` coffee
module.exports.config =

  baseUrl: 'http://localhost:1234/'

  suites:
    all: '**/*.e2e.js'

  capabilities:
    browserName: 'chrome'
    chromeOptions:
      args: [
        '--lang=en'
        '--window-size=1280,1280'
      ]
  chromeDriver: './node_modules/chromedriver/bin/chromedriver'
  seleniumServerJar: './node_modules/selenium-standalone-jar/bin/selenium-server-standalone-2.45.0.jar'

  framework: 'jasmine2'
```

**Comment by NickTomlin** [comment]
That should definitely _not_ be happening, thanks for bringing this to my attention! If you have the time could you try running protractor flake with the `PROTRACTOR_FLAKE_LOG_LEVEL` env variable set to `debug` and post the output?

I'll do my own investigation as well.

**Comment by NickTomlin** [comment]
I can definitely confirm this happens when `--suite` is passed to protractor. I'll start working on this but may not be able to get a fix out for a few days due to scheduling. Feel free to PR something in the meantime.

**Comment by NickTomlin** [comment]
A super hacky fix would be to just remove the `--suite` from the arguments passed to protractor when re-running the specs. I'll push a branch with this fix if you wouldn't mind testing it.

**Comment by NickTomlin** [comment]
Here's the [branch](https://github.com/NickTomlin/protractor-flake/tree/suite). I'm going to see if I can get some integration coverage for it. Would love any feedback you have.

**Comment by bcherny** [comment]
pulling your branch, the behavior is still the same - successful tests are re-run every time.

``` sh
npm i NickTomlin/protractor-flake#suite
cd node_modules/protractor-flake
npm i && npm run build
cd ../..
export PROTRACTOR_FLAKE_LOG_LEVEL=debug
gulp e2e
```

also, setting the log level seems to have no effect..

**Comment by NickTomlin** [comment]
@bcherny interesting, I haven't been able to replicate this :frowning:  Does your project happen to be open sourced? I'd love to pull it down and take a look.

I've set up a [gitter](https://gitter.im/NickTomlin/protractor-flake) room so we can talk about things in a more real-time manner if that suits you better.

**Comment by bcherny** [comment]
i won't be able to take another look till possibly later today. will keep you posted!

**Comment by NickTomlin** [comment]
@bcherny were you able to take another look? I still haven't been able to reproduce, but I want to make sure this isn't happening :)

**Comment by NickTomlin** [comment]
Looks like others are [reproducing this](https://gitter.im/NickTomlin/protractor-flake?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).

**Comment by NickTomlin** [comment]
It appears like this is an issue with Jasmine2 output. @brandonbeyers and I are investigating further.

**Comment by bcherny** [comment]
thanks for the updates! sorry about not helping more, it's been a hectic few weeks.

**Comment by NickTomlin** [comment]
It seems like this was due to jasmine2 output being slightly different than jasmine1 output.
Jasmine one has failed out put like `[object Object].<anonymous> (/path/to/spec.js)` whereas jasmine2 has output like at `Object.<anonymous> (/path/to/spec.js)`.

 I've fixed this in [this branch](https://github.com/NickTomlin/protractor-flake/tree/investigate-%236). @bcherny if you wouldn't mind checking that out and seeing if it resolves your issue i'd much appreciate it. Thanks for your patience!

**Comment by NickTomlin** [comment]
So this is caused by Jasmine2 output (which will be fixed by the changes in the aforementioned branch) or due to a custom reporter that changes the failed spec output from what protractor-flake expects. If you are using a custom reporter you will need to make sure that the original jasmine failures get printed to STDOUT by your tests. @brandonbeyers has a solution for this and is going to PR an addition to the README.

I'm going to merge that branch in and do a new release.

**Comment by brandenbyers** [comment]
Yes, as @NickTomlin says, if working with a custom reporter such as jasmine-spec-reporter, make sure to display stacktraces:

```
onPrepare: function() {
    var SpecReporter = require('jasmine-spec-reporter');
    jasmine.getEnv().addReporter(new SpecReporter({
        displayStacktrace: 'specs'
    }));
}
```

**Comment by el-davo** [comment]
Hi. Is this now fixed. I am still having this issue when i pass in a --suite flag, it runs all tests, I am using version 1.0.1 of this plugin.

**Comment by tedsiebear** [comment]
hm still an issue for me, I am logging stackstrace: displayStacktrace: 'all' or 'specs' and still it is rerunning the whole test suite rather than individual tests that failed, using jasmine2

```
    for (; i < l; i++) {
        if (args[i] === "-t") {
            src.push("spec/e2e/" + args[++i].replace(/\.spec.js$/, "") + ".spec.js");
        }
        if (args[i] === "-f") {
            src.push("spec/e2e/" + args[++i].replace(/\/$/, "") + "/**/*.spec.js");
        }
    }
    if (src.length > 0) {
        protractorArgs.push("--specs", src.join(","));
    }
```

**Comment by okram999** [comment]
when some test fails due to timeout, there is no stacktrace. Its 'undefined'. And hence it ends up re-running all the test. Is this by design?

**Comment by FinKingma** [comment]
@okram999 The default parser only supplies the test specs that can be retrieved with an error stack trace. With timeouts, the test specs are not shown in the error stack trace. So by default there is no way to retrieve the specfile. This results in rerunning all your specs.

If you are using sharding or other types of multitests, you can now also use the multi parser, which assumes that the specfile is shown in the log in the following manner:
Specs: /tests/a-good-test.test.js
This way it can retrieve all the test specs that did not pass (so timeouts will also be rerun).

If this is the case, you can use the multi parser by specifying the following parameter:
parser: 'multi'

When you are still unsure of which parser to use, could you share your logging output with the timeout?

**Comment by quantizor** [comment]
This is still a bug. Using multi and everything gets re-run.

**Comment by wswebcreation** [comment]
Can you give some more info about what you experience?

* Your config
* Your command you use to run protractor-flake
* The log that needs to be parsed


Tnx in advance

**Comment by trevcor** [comment]
I'm seeing a similar issue using the multi parser where any spec that has a pending test will be re-run every time.

**Comment by NickTomlin** [comment]
@trevcor can you provide the following details: 

* Your config
* Your command you use to run protractor-flake
* The log that needs to be parsed

**Comment by naspeh** [comment]
Hey, thanks for hard work!

It works great for other specs, but for this I got all specs running when one spec fails.

this log has spec name
```
Failures:
1) analytics manage activity reports
  Message:
    Expected 2 to equal 1.
  Stack:
    Error: Failed expectation
        at Object.it (/opt/superdesk/client-core/spec/analytics_spec.js:68:47)
        at /opt/superdesk/client-core/node_modules/jasminewd2/index.js:94:23
        at new ManagedPromise (/opt/superdesk/client-core/node_modules/selenium-webdriver/lib/promise.js:1082:7)
        at controlFlowExecute (/opt/superdesk/client-core/node_modules/jasminewd2/index.js:80:18)
        at TaskQueue.execute_ (/opt/superdesk/client-core/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/opt/superdesk/client-core/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/opt/superdesk/client-core/node_modules/selenium-webdriver/lib/promise.js:2820:25)
        at /opt/superdesk/client-core/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:103:7)
Pending:

[...]

Using standard to parse output
Re-running tests: test attempt 2

Tests failed but no specs were found. All specs will be run again.

[...]
```
spec here https://github.com/superdesk/superdesk-client-core/blob/master/spec/analytics_spec.js

----
**Updated:** one more case

```
Failures:
1) search can action on items
  Message:
[31m    Expected false to be true.[0m
  Stack:
    Error: Failed expectation
        at Object.it (/opt/superdesk/client-core/spec/search_spec.js:194:41)
        at /opt/superdesk/client-core/node_modules/jasminewd2/index.js:94:23
        at new ManagedPromise (/opt/superdesk/client-core/node_modules/selenium-webdriver/lib/promise.js:1082:7)
        at controlFlowExecute (/opt/superdesk/client-core/node_modules/jasminewd2/index.js:80:18)
        at TaskQueue.execute_ (/opt/superdesk/client-core/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/opt/superdesk/client-core/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/opt/superdesk/client-core/node_modules/selenium-webdriver/lib/promise.js:2820:25)
        at /opt/superdesk/client-core/node_modules/selenium-webdriver/lib/promise.js:639:7
Pending:

[...]

Using standard to parse output
Re-running tests: test attempt 2

Tests failed but no specs were found. All specs will be run again.

[...]
```
spec: https://github.com/superdesk/superdesk-client-core/blob/master/spec/search_spec.js

**Comment by wswebcreation** [comment]
@NickTomlin,

Looking at the above log it looks like the regex in the [standard.js](https://github.com/NickTomlin/protractor-flake/blob/master/src/parsers/standard.js#L7) parser doesn't give any match. Only `(?:\[object Object\]|Object)` gives a match.
If you look at the testdata we use to test the [jasmine2](https://github.com/NickTomlin/protractor-flake/blob/master/test/unit/support/fixtures/failed-jasmine2-test-output.txt)-output the regex gives  a match on only `at Object.<anonymous>`.
Do you happen to know where the `at Object.it` is coming from? If the `.it` is also an option in jasmine2, we may need to change the regex to 

`at (?:\[object Object\]|Object)\.(?:<anonymous>|it) \((([A-Za-z]:\\)?.*?):.*\)`

Grtz

Wim

**Comment by NickTomlin** [comment]
@wswebcreation great call; I think you are right. I wasn't actually aware that `Object.it` was a jasmine built in. I think your solution sound fair; want to PR it?

**Comment by wswebcreation** [comment]
@NickTomlin,

Will make a PR for it and add a new testcase for it. Hope to do it this weekend. I got 1 question, you say _I wasn't actually aware that Object.it was a jasmine built in_ , do you mean with this that this is new and we need to use it?

Grtz

Wim

**Comment by wswebcreation** [comment]
@naspeh ,

Can you give a complete anonymized log so I can create a correct test for it?
Tnx in advance!

**Comment by naspeh** [comment]
@wswebcreation, sure, here is: https://gist.github.com/naspeh/38a89bb2bdc48a98248e422c725f288d

Thanks for attention and quick feedback!

**Comment by NickTomlin** [comment]
@wswebcreation I was confused because I hadn't seen `Object.it` in Jasmine before. After doing some quick looking I think it's coming from [`jasminewd2`](https://github.com/angular/jasminewd/blob/jasminewd2/index.js#L218) so we should definitely expand the regex.

**Comment by wswebcreation** [comment]
@naspeh 

Tnx. Is this the complete log? I only see 1 failure on 1 spec file (on both examples you gave me). Is that correct?
The link to the superdesk project you provided, is that also the testsetup you are using? `"protractor": "^4.0.13"`?

**Comment by wswebcreation** [comment]
@NickTomlin,

When I create an example project with `"protractor": "^4.0.13"` (if the setup of @naspeh is the same) and run a failed spec I get this logging

``` bash
Failures:
1) angularjs homepage todo list should list todos
  Message:
    Expected 2 to equal 1.
  Stack:
    Error: Failed expectation
        at Object.<anonymous> (/Users/wswebcreation/deTesters/test/example_spec.js:22:32)
        at /Users/wswebcreation/deTesters/test/node_modules/jasminewd2/index.js:94:23
        at new ManagedPromise (/Users/wswebcreation/deTesters/test/node_modules/selenium-webdriver/lib/promise.js:1082:7)
        at controlFlowExecute (/Users/wswebcreation/deTesters/test/node_modules/jasminewd2/index.js:80:18)
        at TaskQueue.execute_ (/Users/wswebcreation/deTesters/test/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/Users/wswebcreation/deTesters/test/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/Users/wswebcreation/deTesters/test/node_modules/selenium-webdriver/lib/promise.js:2820:25)
        at /Users/wswebcreation/deTesters/test/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:103:7)

3 specs, 1 failure
Finished in 4.461 seconds
[08:15:10] I/launcher - 0 instance(s) of WebDriver still running
[08:15:10] I/launcher - chrome #01 failed 1 test(s)
[08:15:10] I/launcher - overall: 1 failed spec(s)
[08:15:10] E/launcher - Process exited with error code 1
```

There the `<anonymous>` is back again. With how many checks should I expand the regex, because I also see more globals in the  [`jasminewd2`](https://github.com/angular/jasminewd/blob/jasminewd2/index.js#L218)-link you provided. If I'm gonna create a PR, I want to fix it all ;-)

Grtz

Wim

**Comment by naspeh** [comment]
> Tnx. Is this the complete log? I only see 1 failure on 1 spec file (on both examples you gave me). Is that correct?

yes this is complete log for protractor step, this is false failing which I want to catch up with `protractor-flake` :)

**Comment by wswebcreation** [comment]
Added a PR for it https://github.com/NickTomlin/protractor-flake/pull/49

**Comment by naspeh** [comment]
Super. Thanks guys, it works, I've just checked new logs with `protractor-flake@2.4.0`

**Comment by wswebcreation** [comment]
Awesome 👍

**Comment by anuvratashu** [comment]
Hi Guys,
Its great work... But its still running all test even there are only 2 test which failed.
node_modules/.bin/protractor-flake --parser multi  --node-bin node  --max-attempts=2 --color=magenta --  JSOut/config.js",

var SpecReporter = require('jasmine-spec-reporter').SpecReporter;
            jasmine.getEnv().addReporter(new SpecReporter({
                displayStacktrace: 'specs'
            })); 

Can you please let me know what else i am missing?

**Comment by wswebcreation** [comment]
Hi @anuvratashu ,

This is a closed issue, please open a new issue if you want, also provide your config, and your log so we can do a detailed check on your problem.

**Comment by vdimikj** [comment]
Hi Guys,

I m facing an issue like this one.
The regex is not catching this one.

```shell
// when test appear
      - Expected '' to be 'Successfully updated page'.
          at UserContext.<anonymous> (/var/www/admin_panel/src/app/e2e/keeping-the-inserted-data.e2e-spec.ts:43:47)
          at /var/www/admin_panel/node_modules/protractor/node_modules/jasminewd2/index.js:112:25
          at new ManagedPromise (/var/www/admin_panel/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1067:7)
          at ControlFlow.promise (/var/www/admin_panel/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2396:12)
          at schedulerExecute (/var/www/admin_panel/node_modules/protractor/node_modules/jasminewd2/index.js:95:18)
          at TaskQueue.execute_ (/var/www/admin_panel/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2970:14)
          at TaskQueue.executeNext_ (/var/www/admin_panel/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2953:27)
          at asyncRun (/var/www/admin_panel/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2860:25)
          at /var/www/admin_panel/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:676:7
```

This is solvable by updating the old regex
at `(?:\[object Object\]|Object)\.(?:<anonymous>|it) \((([A-Za-z]:\\)?.*?):.*\)`
to
at `(?:\[object Object\]|Object|UserContext)\.(?:<anonymous>|it) \((([A-Za-z]:\\)?.*?):.*\)`

Though i m using SpecReporter, Jasmine, and starting flake with standard parser

Thanks,
Vlad

**Comment by NickTomlin** [comment]
@VladimirDimikjCuponation interesting, i'm not sure if this is a common thing? You could solve this by writing a custom parser for yourself, or, if this is part of jasmine, we could just incorporate it into the standard parser.

**Comment by wswebcreation** [comment]
@NickTomlin 

I think this has to do with the SpecReporter, see also [here](https://github.com/NickTomlin/protractor-flake/issues/54#issuecomment-309643992). I read a lot about the spec reporter, should we think about supporting that?

**Comment by NickTomlin** [comment]
Interesting, the `UserContext` error seems different than the spec reporter (e.g. the spec reporter output doesn't have any stack trace information) but I agree that it is an issue.

 Since Jasmine supports multiple reports (IIRC) I wonder if we could do something like add a custom flake reporter that would write the output to a file or communicate with flake in some other way. Sounds slightly complicated though, do you have any thoughts?

**Comment by wswebcreation** [comment]
Having a few weeks off so plenty of time to think about it 😊

**Comment by vdimikj** [comment]
@NickTomlin @wswebcreation  any updates on this one?

**Comment by wswebcreation** [comment]
@vdimikj 

Currently not, I'm thinking about a different solution. But because people SpecReporter and want a clean report no stacktrace and and other logging is shown. That extra logging is needed by protractor-flake to read the logging and find the failing spec files.
I would suggest to change some settings in you SpecReporter initialisation, see [here](https://github.com/bcaudan/jasmine-spec-reporter/blob/745ee96896a2bc71a9f1364d620e924ea58957eb/src/configuration.ts) to get the right logging that protractor-flake can pick up.

**Comment by vdimikj** [comment]
Resolved with this PR
- https://github.com/NickTomlin/protractor-flake/pull/70
Thanks

**Comment by NickTomlin** [comment]
👍  thanks for reporting back in
